### PR TITLE
Issue #40 #41 #38 Employee Profile Build out Flow Fix

### PR DESCRIPTION
**Pull request by srajas0**

### CODE REVIEW

**Comment by srajas0** [comment]
@mahestro This issue depends on https://github.com/topcoderinc/mjolnir-web/issues/41 also, So don't merge it until issue https://github.com/topcoderinc/mjolnir-web/issues/41 finished. Do review only.

**Comment by mahestro** [comment]
Looks great so far. Just needs to move the import profile popup into the step one http://take.ms/gB7Y0

**Comment by srajas0** [comment]
@mahestro I have fixed issue #41 #38 along with this PR

**Comment by srajas0** [comment]
Just needs to move the import profile popup into the step one http://take.ms/gB7Y0

@mahestro I think this issue is fixed in latest commit.

**Comment by mahestro** [comment]
Just checked the PR - AWESOME job, the flows have been fixed.

One thing, this is still missing: http://take.ms/gB7Y0 (expected) - right now: http://take.ms/bGOlX – This has to be fixed in both Employee and Employer profiles. The popup should show over step one (with the UI fields underneath).

**Pull request merged**
